### ISSUE TITLE
Find a way to have custom anchors in Github-rendered .org documents

### ISSUE THREAD

**Issue by Matrixcoffee** [Matrixcoffee/matrix-knowledge-base#10]

**Comment by Matrixcoffee** [comment]
Tests so far:
- **FAIL** Using `:PROPERTIES: :CUSTOM_ID: text`
- **FAIL** Using `<<text>>`
- What else to try?

**Comment by Matrixcoffee** [comment]
Solution: use `@@html:<a name="word">@@` syntax as a workaround.

**Comment by Matrixcoffee** [comment]
Which can't be used in properties, because that is hidden. It has to be uglily added to the title itself. Best at the end, so that when lines get truncated I see the actual title, not just the frankenID.

So that's:
`* Some title @@html:<a name="custom-id">@@`

Also consider filing a bug on [[/wallyqs/org-ruby]]. Issues wallyqs/org-ruby#11 and wallyqs/org-ruby#41 seem related.

**Comment by Matrixcoffee** [comment]
Above solution is not perfect, but good enough I guess. Closing this now.

**Comment by mgoldenbe** [comment]
With this solution, clicking on a link results in jumping to the text _after_ the title. The title itself ends up being above the visible part of the page...

**Comment by mgoldenbe** [comment]
OK. To avoid jumping to the wrong line, the solution should look like this:
```
@@html:<a name="custom-id">@@
* Some title
```

**Comment by Matrixcoffee** [comment]
Thanks for pitching in.

Annoyingly, orgzly doesn't let you place contents above the title like that.

**Comment by mgoldenbe** [comment]
What's `orgzly`? I have it [working](https://github.com/mgoldenbe/literef) though...

**Comment by mgoldenbe** [comment]
I use `Emacs` under `Ubuntu`. That way it worked.

**Comment by Matrixcoffee** [comment]
Emacs doesn't run very well on my phone I'm afraid. Anyway, anything we come up with here is only temporary until we have a solution for #9.
