### ISSUE TITLE
Promote Changelog Info' for the Synapse UX and Admin' of Rooms or Homeservers

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [Matrixcoffee/matrix-knowledge-base#44]
Basically a purpose for this repo' project is to help users and Admin's or Dev'Op's know how things are actually supposed to work **currently**.  This is desperately needed, and in the virtual pipeline herein.  ¶  **BUT** when development pushes changes, we need to be aware of approximately when they will take effect, and how they effect the UX.  So entries should reflect expected change rollouts so we're not «working in the dark with the lights on».  :-/

**Comment by Matrixcoffee** [comment]
I'm afraid I only have a vague idea of what this means. MKB documents current solutions to common problems, so it is bound to lag behind changes. If something has changed recently, of course it makes sense to also keep the old solution for a while.

I don't see how this is actionable, so closing.
