### ISSUE TITLE
Enable a Wiki for the Repository.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [Matrixcoffee/matrix-knowledge-base#46]
In the past it has been suggested to the Vector Creations Ltd. Dev'Op's to enable a Wiki on their Spec'/Doc's repo'.  That was before this effort.  `¶`But, to get community driven Q&A/FAQ written for, and by, End Users, newbies, and those not skimming the latest Source Code PRs for answers, enable a Wiki.  `¶`The GitHub Wiki automatically creates anchors for sections headers of articles, and the fragment links.  So, those are easily dropped in Matrix rooms as very specific answers by humans or bots.

**Comment by Matrixcoffee** [comment]
Hi MilkManzJourDaddy, thanks for your suggestion. I've thought about it, and feel that opening a separate wiki will lead to unwanted fragmentation. The place to add short bits of information is into the MKB itself.

Most matrix projects have a wiki page which is enabled, and I feel that longer texts should go there, with MKB giving a short description and a link.

**Comment by Matrixcoffee** [comment]
Closing for now, which is not to say this is the final word on it.

**Comment by Matrixcoffee** [comment]
Hmm. I just tried to work with GitHub's wiki system, and it's difficult to discuss and coordinate changes. That will be a problem with complex or controversial changes. Definitely won't be using GitHub's wiki pages. Maybe a real wiki hosted elsewhere, someday.
